version: '3'

services:
  aeternity:
    container_name: aeternity
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - DATA_DIR=/.aeternity
    env_file: env
    restart: unless-stopped
#     volumes:
#       - /docker-aeternity:"${DATA_DIR}"
# volumes:
#   docker-aeternity: